apiVersion: v1
kind: Service
metadata:
  name: breast-cancer-service
spec:
  type: NodePort
  selector:
    app: breast-cancer-api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      nodePort: 30000
    - name: metrics
      port: 8001
      targetPort: 8001
      nodePort: 30001